---
abstract: 'Find corresponding files in the directory tree'
author:
  - 'Johan Lindstrom <johanl@cpan.org>'
build_requires:
  File::chdir: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Corresponding
no_index:
  directory:
    - t/data
requires:
  Data::Dumper: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Path: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Pod::Usage: 0
  YAML::Tiny: 0
  lib: 0
  strict: 0
version: 0.004
